Branchpull/1
OhMyAgnes/blob-rpc-server pull request #3
Opened 2022-05-15 06:48 UTC by ZR19971001

2022-05-17 01:56 UTC, OhMyAgnes requested changes
直接写makefile也行， 但是还要完成cmake部分。

2022-05-17 01:56 UTC, OhMyAgnes commented on sdk/myclass/src/myclass.cpp
> +int ReadImage::getSum()
如果输入是三通道，还需要先转换成grayscale

2022-05-17 01:58 UTC, OhMyAgnes commented
另外，提交信息的格式不符合标准。（以后注意）

2022-05-17 14:01 UTC, ZR19971001 commented on sdk/myclass/src/myclass.cpp
> +int ReadImage::getSum()
我在main.cpp里面的第11行，读图的时候就已经转为单通道了

2022-05-20 09:14 UTC, OhMyAgnes requested changes

2022-05-20 09:14 UTC, OhMyAgnes commented on sdk/CMakeLists.txt
> +include_directories(${OpenCV_INCLUDE_DIRS})
这种最好放到子文件夹里，哪个target用到再include

2022-05-24 11:38 UTC, merged